channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numba=0.57.0
  - astropy=7.0.1
  - scikit-learn=1.6.1 
  - matplotlib=3.10.1
  - scipy=1.15.2
  - numpy=1.24.4
  - xarray=2025.4.0
  - pip:
    - spectral==0.24
    - ray==2.45.0
    - xxhash==3.5.0