channels:
  - conda-forge
dependencies:
  - astropy
  - gdal=3.11.4
  - matplotlib
  - opencv
  - numba
  - numpy
  - python=3.11
  - scikit-image
  - scikit-learn
  - scipy
  - xarray
  - pip=25.1.1 
  - pip:
    - ray==2.45.0
    - spectral==0.24
    - xxhash==3.5.0